export const colors = {
    COLOR_PRIMARY: "green",
    COLOR_LIGHT: "#fff",
    COLOR_DARK: "#000",
    COLOR_DARK_ALT: "262626",
}

export const categories = [
    {
        id: "01",
        category: "Breakfast",
    },
    {
        id: "02",
        category: "Lunch",
    },
    {
        id: "03",
        category: "Dinner",
    },
    {
        id: "04",
        category: "Dessert",
    },
    {
        id: "05",
        category: "Snacks",
    },
];

export const recipeList = [
    {
        id: "02",
        name: "Akara and Bread",
        image: require("../assets/images/akara_and_bread2.jpg"),
        rating: "4.2",
        ingredients: ["2 cups of peeled beans", "1 medium onion", "2-3 fresh chili peppers (optional)",  "Salt to taste", "Vegetable oil for frying", "Ground crayfish", "Maggi"],        time: "30 mins",
        difficulty: "None",
        calories: "190 cal",
        color: "darksalmon",
        description: "Akara is a popular Nigerian street food made from peeled beans, onions, and spices. It is deep-fried until golden brown and typically served as a snack or breakfast item.",
        steps: [
        "Soak the peeled beans in water for at least 3 hours or overnight to soften them",
        "Drain the soaked beans and blend them with the onion and chili peppers until smooth.",
        "Add salt to taste and mix well.",
        "Heat the vegetable oil in a deep frying pan. Scoop the bean batter using a spoon and carefully drop it into the hot oil.",
        "Fry the akara balls until they are golden brown and crispy on the outside, about 5-7 minutes.",
        "Remove the fried akara from the oil and drain on paper towels to remove excess oil.",
        "Serve the akara hot with bread, or as a standalone snack"
    ],
    },
    {
        id: "03",
        name: "Bread and Egg",
        image: require("../assets/images/bread_egg.jpg"),
        rating: "4.8",
        ingredients: ["Vegetable oil Or butter", "Bread",  "Eggs",  "Pepper",  "Onion",  "Maggi",  "Salt", "Tomatoes"],
        time: "20 mins",
        difficulty: "None",
        calories: "250 cal",
        color: "darkseagreen",
        description: "Bread and Egg is a simple and delicious breakfast dish made by frying eggs and serving them with bread",
        steps: [
        "Heat a frying pan over medium heat",
        "crack the eggs into a small bowl and beat them lightly with a fork or whisk",
        "Season with salt and pepper to taste.",
        "Once the pan is hot, add a small amount of butter or oil to coat the bottom of the pan.",
        "Pour the beaten eggs into the pan, tilting the pan slightly to spread them out evenly.",
        "Allow the eggs to cook ",
        "Using a spatula, gently lift the edges of the eggs and tilt the pan to allow any uncooked egg to flow underneath",
        "Once the eggs are cooked, remove them from the pan and place them on top of the bread slices",
        ],
    },
    {
        id: "04",
        name: "Garri and Groundnut",
        image: require("../assets/images/garri_groundnut.jpg"),
        rating: "5.0",
        ingredients: ["Garri" , "Groundnut", "Water", "Sugar or salt"],
        time: "2 mins",
        difficulty: "None",
        calories: "190 cal",
        color: "darkolivegreen",
        description: "Garri and groundnut is a popular West African snack or meal made from cassava flakes (garri) and roasted peanuts (groundnut)",
        steps: [
        "Place the desired amount of garri in a bowl",
        "mix the groundnut with the garri in the bowl.",
        "Garri and groundnut can be served as is, or you can add sugar or salt to taste if desired",
        ],
    },
    {
        id: "14",
        name: "Toast",
        image: require("../assets/images/toast.jpg"),
        rating: "5.0",
        ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],        time: "30 mins",
        difficulty: "None",
        calories: "400 cal",
        color: "forestgreen",
        description: "he savory flavors of sausages and chicken with the comforting crunch of toast",
        steps: [
        "Slice the cooked chicken breast into thin strips",
        "Heat a frying pan over medium heat and add the sausages. Cook them until they are browned and cooked through, about 8-10 minutes",
        "In the same frying pan, melt the butter over medium heat",
        "Place the slices of bread in the pan and toast them until they are golden brown on both sides, about 2-3 minutes per side",
        "Place the toasted bread slices on a plate",
        "Top each slice with a portion of the cooked chicken breast strips and a sausage",
        "Season with salt and pepper to taste."
        ],
    },
    {
        id: "06",
        name: "Indomie",
        image: require("../assets/images/indomie.jpg"),
        rating: "4.0",
        ingredients: ["Indomie noodles", "Onion", "Hot pepper",  "Salt", "1 tablespoon of vegetable oil", "water", ],
        time: "30 mins",
        difficulty: "Medium",
        calories: "400 cal",
        color: "mediumseagreen",
        description: "Indomie with Eggs is a simple and delicious noodle dish that is quick and easy to prepare",
        steps: [
        "Fill a pot with water and bring it to a boil.",
        "Once the water is boiling, add the Indomie noodles and cook for about 3 minutes or until they are soft. ",
        "Drain the noodles and set aside",
        "In a separate pan, heat vegetable oil over medium heat. Crack the eggs into the pan and cook them sunny-side-up or scrambled, according to your preference.",
        "Season with salt and pepper, Add chopped onion, tomato, and green pepper to the pan with the eggs. Cook until the vegetables are soft and fragrant",
        "Add the cooked Indomie noodles to the pan with the eggs and vegetables. Stir well to combine all the ingredients",
        "Once everything is heated through and well combined, remove the pan from the heat. Serve the Indomie with Eggs hot and enjoy",
        ],
    },
    {
        id: "07",
        name: "Moimoi and Pap",
        image: require("../assets/images/moimoi_and_pap.jpg"),
        rating: "4.8",
        ingredients: ["washed beans", "Onion", "Hot pepper",  "Banana leaves or foil for wrapping", "Salt to taste", "Vegetable oil", "Ground crayfish", "Seasoning cubes", "Cornmeal or maize flour", "Water", "Sugar or sweetener (optional)","Milk (optional)"],        
        time: "i hour 35 mins",
        difficulty: "Medium",
        calories: "180 cal",
        color: "teal",
        description: "Moi Moi is a Nigerian steamed bean pudding made from ground peeled beans, seasoned with spices and steamed until set.",
        steps: [
        "Rinse the beans thoroughly and soak them in water for at least 4 hours or overnight to soften.",
        "Drain the soaked beans and transfer them to a blender or food processor.",
        "Add chopped onion, red bell pepper, scotch bonnet pepper (if using), vegetable oil, crayfish (if using), maggi, and salt to the blender.",
        "Blend the mixture until smooth, adding a little water if necessary to achieve a thick but pourable consistency.",
        "Preheat a large pot with water for steaming, Line small bowls, ramekins, or aluminum foil with banana leaves or oil to prevent sticking.",
        "Pour the blended bean mixture into the prepared containers, filling them about two-thirds full.",
        "Place the containers in the pot with simmering water and steam the Moi Moi for about 1 hour or until firm and cooked through.",
        "remove the Moi Moi from the heat and let them cool slightly before serving.",
        "In a separate bowl, mix the cornmeal or maize flour with a small amount of cold water to form a smooth paste.",
        "Gradually pour the cornmeal paste into the boiling water while stirring continuously to prevent lumps from forming.",
        "Continue stirring the mixture over medium heat until it thickens to your desired consistency, similar to porridge.",
        "If desired, sweeten the Pap with sugar or your preferred sweetener, and add milk for creaminess if desired.",
        "Serve the warm Moi Moi and Pap together for a delicious and satisfying meal."
        ],
    },
    {
        id: "08",
        name: "Pancakes",
        image: require("../assets/images/pancakes.jpg"),
        rating: "4.2",
        ingredients: ["All-purpose flour", "Milk", "Egg", "Sugar", "Baking powder", "Salt", "Butter or oil (for greasing the pan)", "Optional toppings: maple syrup, fresh fruit, whipped cream, chocolate chips"],        
        time: "30 mins",
        difficulty: "Easy",
        calories: "80 cal",
        color: "cadetblue",
        description: " Pancakes are a classic breakfast favorite loved for their fluffy texture and versatility. They can be enjoyed plain or topped with a variety of sweet or savory toppings, making them perfect for any time of day.",
        steps: [
        "In a mixing bowl, combine the all-purpose flour, sugar, baking powder, and salt.",
        "In a separate bowl, beat the egg and then stir in the milk.",
        "Pour the wet ingredients into the dry ingredients and mix until just combined. Be careful not to overmix; some lumps are okay.",
        "Heat a non-stick skillet or griddle over medium heat and grease it with butter or oil.",
        "Pour a ladleful of the pancake batter onto the hot skillet, using about 1/4 cup of batter for each pancake.",
        "Cook until bubbles form on the surface of the pancake and the edges look set, about 2-3 minutes.",
        "Flip the pancake and cook for an additional 1-2 minutes until golden brown and cooked through.",
        "Repeat with the remaining batter, greasing the skillet as needed."
        ],
    },
    {
        id: "09",
        name: "Pap and Akara",
        image: require("../assets/images/pap_and_akara2.jpg"),
        rating: "4.5",
        ingredients: ["Cornmeal or maize flour","Water","Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],        
        time: "30 mins",
        difficulty: "moderate",
        calories: "90 cal",
        color: "paleturquoise",
        description: "Akara is a popular Nigerian street food made from peeled and blended black-eyed peas, seasoned with onions, and deep-fried until crispy on the outside and soft on the inside.",
        steps: [
        "In a bowl, mix the cornmeal or maize flour with a small amount of water to form a smooth paste.",
        "Boil the remaining water in a pot.",
        "Gradually add the cornmeal mixture to the boiling water while stirring continuously to prevent lumps from forming.",
        "Continue stirring and cooking the mixture over medium heat for about 10-15 minutes, or until it thickens to your desired consistency.",
        "Remove from heat and let it cool slightly before serving.",
        "Soak the black-eyed peas in water for several hours or overnight to soften them.",
        "Drain the soaked beans and transfer them to a blender or food processor.",
        "Add chopped onion, scotch bonnet peppers (if using), and salt to the blender.",
        "Blend the mixture until smooth, adding a small amount of water if necessary to facilitate blending.",
        "Heat vegetable oil in a deep frying pan or pot over medium heat.",
        "Using a spoon or your hands, scoop small portions of the bean mixture and carefully drop them into the hot oil.",
        "Fry the akara in batches, turning occasionally, until golden brown and crispy on all sides.",
        "Once cooked, remove the akara from the oil and drain on paper towels to remove excess oil.",
        "Serve hot with pap, and enjoy!"
        ],
    },
    {
        id: "10",
        name: "Plantain and egg",
        image: require("../assets/images/plantain_and_egg.jpg"),
        rating: "4.9",
        ingredients: ["Ripe plantains", "Eggs", "Vegetable oil", "Onion (chopped)", "Tomatoes (chopped)", "Bell peppers (chopped)", " peppers (optional, chopped)", "Salt", "Black pepper", "Ground crayfish (optional)", "Fresh parsley or coriander (optional, for garnish)"],        
        time: "25 mins",
        difficulty: "Easy",
        calories: "230 cal",
        color: "darkslateblue",
        description: "Plantain and Egg is a simple and delicious Nigerian dish that combines ripe plantains with scrambled eggs, sautéed vegetables, and spices. It's a popular breakfast or brunch option but can also be enjoyed as a light lunch or dinner.",
        steps: [
        "Heat vegetable oil in a skillet or frying pan over medium heat.",
        "Add the plantain cubes to the hot oil and fry until golden brown and cooked through, turning occasionally to ensure even cooking.",
        "Once cooked, transfer the fried plantains to a plate lined with paper towels to drain excess oil.",
        "In the same skillet or frying pan, add a little more oil if needed.",
        "Add the chopped onion to the pan and sauté until translucent.",
        "Add the chopped tomatoes and bell peppers to the pan and cook until softened.",
        "If using, add the chopped scotch bonnet peppers for extra heat.",
        "Season the vegetable mixture with salt, black pepper, and ground crayfish (if using), and stir to combine.",
        "Pour the beaten eggs over the sautéed vegetables in the skillet.",
        "Allow the eggs to cook for a few seconds, then gently stir and scramble them with the vegetables until they are cooked to your desired consistency.",
        "Once the eggs are cooked, add the fried plantains to the skillet and gently mix everything together.",
        "Taste and adjust seasoning if necessary."
        ],
    },
    {
        id: "11",
        name: "Yam and Egg",
        image: require("../assets/images/yam_and_egg.jpg"),
        rating: "4.7",
        ingredients: ["Yam (peeled and sliced into rounds or cubes)", "Eggs", "Onion (chopped)", "Tomatoes (chopped)", "Bell peppers (chopped)", "Vegetable oil", "Salt", "Black pepper (optional)"],       
        time: "40 mins",
        difficulty: "Medium",
        calories: "200 cal",
        color: "lavender",
        description: "Yam and Egg is a simple and nutritious Nigerian dish that combines boiled or fried yam with scrambled eggs and flavorful vegetables. It's a popular breakfast or brunch option and can also be enjoyed as a light lunch or dinner.",
        steps: [
        "Peel the yam and slice it into rounds or cubes, depending on your preference.",
        "Chop the onion, tomatoes, and bell peppers.",
        "If boiling, place the yam slices or cubes in a pot of water and bring to a boil. Cook until tender, then drain and set aside.",
        "If frying, heat vegetable oil in a pan over medium heat. Fry the yam slices or cubes until golden brown and cooked through. Remove from the oil and drain on paper towels to remove excess oil.",
        "In a bowl, crack the eggs and whisk them until well beaten.",
        "Add chopped onion, tomatoes, and bell peppers to the beaten eggs. Season with salt and black pepper if desired. Mix well.",
        "Heat a little vegetable oil in a pan over medium heat.",
        "Pour the egg mixture into the hot pan and allow it to cook without stirring for a minute or two until the bottom starts to set.",
        "Using a spatula, gently stir and fold the eggs until they are cooked through but still moist and slightly runny.",
        "Once the eggs are cooked, add the boiled or fried yam to the pan with the eggs.",
        "Gently toss the yam and eggs together until they are evenly combined and heated through.",
        "Transfer the yam and egg mixture to a serving platter."
        ],
    },
    {
        id: "12",
        name: "Toast",
        image: require("../assets/images/toast.jpg"),
        rating: "4.2",
        ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],        time: "30 mins",
        difficulty: "None",
        calories: "190 cal",
        color: "mediumpurple",
        description: "classic agege bread, with plumpy akara",
        steps: [
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        ],
    },
    {
        id: "13",
        name: "Toast",
        image: require("../assets/images/toast.jpg"),
        rating: "4.2",
        ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],
        time: "30 mins",
        difficulty: "None",
        calories: "190 cal",
        color: "rosybrown",
        description: "classic agege bread, with plumpy akara",
        steps: [
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
        ],
    },
]

// export const recipeDessert = [
//     {
//         id: "14",
//         name: "Toast",
//         image: require("../assets/images/toast.jpg"),
//         rating: "4.2",
//         ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],
//         time: "30 mins",
//         difficulty: "None",
//         calories: "190 cal",
//         color: "rosybrown",
//         description: "classic agege bread, with plumpy akara",
//         steps: [
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         ],
//     },
//     {
//         id: "17",
//         name: "Toast",
//         image: require("../assets/images/toast.jpg"),
//         rating: "4.2",
//         ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],
//         time: "30 mins",
//         difficulty: "None",
//         calories: "190 cal",
//         color: "rosybrown",
//         description: "classic agege bread, with plumpy akara",
//         steps: [
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         ],
//     },
// ]

// export const recipeLunch = [
//     {
//         id: "15",
//         name: "Amala and Ewedu",
//         image: require("../assets/images/amala_ewedu.jpeg"),
//         rating: "4.0",
//         ingredients: ["Yam flour", "Water", "Hot pepper",  "Salt", "Ewedu leaves", "Ground crayfish", "Maggi", "Locust beans (iru)"],
//         time: "50 mins",
//         difficulty: "Moderate",
//         calories: "300 cal",
//         color: "rosybrown",
//         description: "Amala is a popular Nigerian swallow made from yam flour, while Ewedu is a traditional soup made from jute leaves. Amala is typically served with Ewedu soup along with assorted meat or fish stew.",
//         steps: [
//         "Boil water in a pot, Gradually add yam flour to the boiling water while stirring continuously to prevent lumps from forming.",
//         "Keep stirring until the mixture thickens and becomes smooth.",
//         "Once it reaches the desired consistency, remove from heat and set aside.",
//         "Wash the ewedu leaves thoroughly and place them in a pot with enough water to cover them.",
//         "Boil the jute leaves until they are tender",
//         "transfer the ewedu leaves to a blender or food processor and blend until smooth.",
//         "Return the blended jute leaves to the pot and add ground crayfish, locust beans, salt, bouillon cube (if using), and cayenne pepper (if desired).",
//         "Simmer the mixture for another 5-10 minutes, stirring occasionally, until it thickens to your desired consistency.",
//         "Serve the hot Amala with Ewedu soup alongside your choice of stewed meat or fish.",
//         ],
//     },
//     {
//         id: "30",
//         name: "White Spaghetti and Stew",
//         image: require("../assets/images/white_spag.jpeg"),
//         rating: "3.9",
//         ingredients: ["Spaghetti pasta", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Water", "Maggi", "Assorted meats or fish (optional)", "Tomato paste", "Red bell peppers", "Tomatoes"],
//         time: "1 hour",
//         difficulty: "high",
//         calories: "190 cal",
//         color: "rosybrown",
//         description: "White Spaghetti and Stew is a popular Nigerian dish enjoyed as a main course. The spaghetti is boiled until tender and served with a rich and flavorful tomato-based stew, often accompanied by assorted meats or fish.",
//         steps: [
//         "Bring a large pot of water to a boil, add salt to the boiling water.",
//         "Break the spaghetti into halves or thirds and add it to the boiling water.",
//         "Cook the spaghetti, Once cooked, drain the spaghetti and set it aside.",
//         "Blend tomatoes, red bell peppers, onion, and scotch bonnet peppers (if using) until smooth to make the base for the stew.",
//         "Heat vegetable oil in a large pot or saucepan over medium heat.",
//         "Add the blended tomato-pepper mixture to the hot oil and fry, stirring occasionally, until the mixture thickens and the oil begins to separate",
//         "Add bouillon cubes, salt, and any desired seasoning to taste.",
//         "If using meats or fish, add them to the stew at this stage and cook until they are fully cooked through.",
//         "Add water to achieve your desired consistency for the stew and simmer for an additional 10-15 minutes, allowing the flavors to meld together."
//         ],
//     },
//     {
//         id: "31",
//         name: "Yam Pepper Soup",
//         image: require("../assets/images/yam_peppersoup.jpg"),
//         rating: "4.9",
//         ingredients: ["Yam ", "Onion", "Hot pepper",  "Salt", "Assorted meats", "Garlic", "Maggi", "Ginger", "water", "scent leaves"],
//         time: "45 mins",
//         difficulty: "moderate",
//         calories: "190 cal",
//         color: "rosybrown",
//         description: "Yam Pepper Soup is a spicy and aromatic Nigerian soup made with yam and a flavorful pepper soup broth",
//         steps: [
//         "Peel the yam and cut it into bite-sized cubes, Rinse the assorted meats thoroughly and cut them into smaller pieces if necessary.",
//         "Chop the onion, mince the garlic and ginger, and slice the fresh peppers.",
//         "Add chopped onion, minced garlic, minced ginger, salt, and maggi cubes to the pot",
//         "",
//         "",
//         "",
//         "",
//         ],
//     },
//     {
//         id: "32",
//         name: "Pounded yam and Okoro soup",
//         image: require("../assets/images/yam_okoro.jpeg"),
//         rating: "4.9",
//         ingredients: ["Yam ", "Onion", "Hot pepper",  "Salt", "Assorted meats", "Garlic", "Maggi", "Ginger", "water", "scent leaves"],
//         time: "45 mins",
//         difficulty: "moderate",
//         calories: "190 cal",
//         color: "rosybrown",
//         description: "Yam Pepper Soup is a spicy and aromatic Nigerian soup made with yam and a flavorful pepper soup broth",
//         steps: [
//         "Peel the yam and cut it into bite-sized cubes, Rinse the assorted meats thoroughly and cut them into smaller pieces if necessary.",
//         "Chop the onion, mince the garlic and ginger, and slice the fresh peppers.",
//         "Add chopped onion, minced garlic, minced ginger, salt, and maggi cubes to the pot",
//         "",
//         "",
//         "",
//         "",
//         ],
//     },
// ]

// export const recipeDinner = [
//     {
//         id: "18",
//         name: "Toast",
//         image: require("../assets/images/toast.jpg"),
//         rating: "4.2",
//         ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],
//         time: "30 mins",
//         difficulty: "None",
//         calories: "190 cal",
//         color: "rosybrown",
//         description: "classic agege bread, with plumpy akara",
//         steps: [
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         ],
//     },
//     {
//         id: "19",
//         name: "Toast",
//         image: require("../assets/images/toast.jpg"),
//         rating: "4.2",
//         ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],
//         time: "30 mins",
//         difficulty: "None",
//         calories: "190 cal",
//         color: "rosybrown",
//         description: "classic agege bread, with plumpy akara",
//         steps: [
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         ],
//     },
// ]

// export const recipeSnacks = [
//     {
//         id: "22",
//         name: "Toast",
//         image: require("../assets/images/toast.jpg"),
//         rating: "4.2",
//         ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],
//         time: "30 mins",
//         difficulty: "None",
//         calories: "190 cal",
//         color: "rosybrown",
//         description: "classic agege bread, with plumpy akara",
//         steps: [
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         ],
//     },
//     {
//         id: "21",
//         name: "Toast",
//         image: require("../assets/images/toast.jpg"),
//         rating: "4.2",
//         ingredients: ["Beans", "Onion", "Hot pepper",  "Salt", "Vegetable oil", "Ground crayfish", "Maggi"],
//         time: "30 mins",
//         difficulty: "None",
//         calories: "190 cal",
//         color: "rosybrown",
//         description: "classic agege bread, with plumpy akara",
//         steps: [
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         "idnqiwdnwiqnddnwwiodnwiqondiwqndwdnqonwdqj",
//         ],
//     },
// ]

